# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2022-03-15 17:02
from __future__ import unicode_literals

from django.db import migrations, models


PART_SQL = [
    "CREATE TABLE part (id INTEGER PRIMARY KEY,name VARCHAR(150),sku VARCHAR(30),description VARCHAR(1024),weight_ounces INTEGER,is_active TINYINT(1));",
    "INSERT INTO part (name, sku, description, weight_ounces, is_active) VALUES ('Heavy coil', 'SDJDDH8223DHJ', 'Tightly wound nickel-gravy alloy spring', 22, 1);",
    "INSERT INTO part (name, sku, description, weight_ounces, is_active) VALUES ('Reverse lever', 'DCMM39823DSJD', 'Attached to provide inverse leverage', 9, 0);",
    "INSERT INTO part (name, sku, description, weight_ounces, is_active) VALUES ('Macrochip', 'OWDD823011DJSD', 'Used for heavy-load computing', 2, 1);",
]

PART_REVERSE_SQL = "DROP TABLE part;"


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [migrations.RunSQL(PART_SQL, PART_REVERSE_SQL)]
